-- INSERT INTO D_FORMA_PAG
INSERT INTO D_FORMA_PAGO (
    COD_FORMA_PAGO, 
    DESC_FORMA_PAGO, 
    REQUIERE_NRO_COMPROBANTE,
    PORCENTAJE_DESCUENTO,
    PORCENTAJE_RECARGO
) VALUES (
    (SELECT MAX(COD_FORMA_PAGO) FROM D_FORMA_PAGO)+1,
    'CONTADO OUTLET', 
    1, 
    30, 
    0
);

-- INSERT INTO D_PRODUCTOS_MEDIDA_PRECIO
INSERT INTO D_PRODUCTOS_MEDIDA_PRECIO (
    ID_REGISTRO,
    PRECIO_VENTA,
    ID_PRODUCTO,
    COD_MEDIDA,
    COD_SUCURSAL,
    COD_FORMA_PAGO
) VALUES (
    (SELECT MAX(ID_REGISTRO) FROM D_PRODUCTOS_MEDIDA_PRECIO)+1,
    (SELECT PRECIO_ULTIMA_COMPRA, FECHA_ULTIMA_COMPRA FROM D_PRODUCTOS 
      WHERE FECHA_ULTIMA_COMPRA NOT BETWEEN MAX(FECHA_ULTIMA_COMPRA) - 365 AND MAX(FECHA_ULTIMA_COMPRA)  
      ORDER BY FECHA_ULTIMA_COMPRA DESC
    ),