-- item 3
-- BOCETO
SELECT O.DESC_OPERACION AS Tipo,
    TO_CHAR(
        NVL(SUM(
            CASE 
                WHEN TPIVA.DESC_TIPO_IVA = 'IVA 10%' THEN DO.PRECIO_OPERACION
            END    
        ), 0)
    , '999G999G999') AS Monto_10,
    TO_CHAR(
        NVL(SUM(
            CASE 
                WHEN TPIVA.DESC_TIPO_IVA = 'IVA 10%' THEN DO.PRECIO_OPERACION
            END    
        ), 0)
    ,'999G999G999') AS IVA_10,
    TO_CHAR(
        NVL(SUM(
            CASE 
                WHEN TPIVA.DESC_TIPO_IVA = 'IVA 5%' THEN DO.PRECIO_OPERACION
            END    
        ), 0)
    ,'999G999G999') AS Monto_5,
    TO_CHAR(NVL(SUM(
            CASE
                WHEN TPIVA.DESC_TIPO_IVA = 'IVA 5%' THEN DO.IMPORTE_IVA
            END
        ), 0)
    , '999G999G999') AS IVA_5
FROM  D_DETALLE_OPERACIONES DO
JOIN D_MOVIMIENTO_OPERACIONES DMO
ON DO.ID_OPERACION = DMO.ID_OPERACION
JOIN D_TIPO_IVA TPIVA
ON DO.COD_TIPO_IVA = TPIVA.COD_TIPO_IVA
JOIN D_OPERACIONES O
ON DMO.COD_OPERACION = O.COD_OPERACION
WHERE DMO.TIPO_REGISTRO LIKE '%A%' 
AND (O.DESC_OPERACION LIKE '%VENTA%'
OR O.DESC_OPERACION LIKE '%COMPRA%')
GROUP BY O.DESC_OPERACION
ORDER BY O.DESC_OPERACION DESC;
---------------------------


-- INSERT TABLE
INSERT INTO D_MOVIMIENTO_OPERACIONES (
    ID_OPERACION,
    FECHA_OPERACION,
    COD_SUCURSAL,
    COD_OPERACION,
    ID_PERSONA,
    NRO_CAJA,
    ID_USUARIO,
    COD_TIPO_COMPROBANTE,
    NRO_COMPROBANTE,
    TIPO_REGISTRO,
    DESCRIPCION_OPERACION,
    NRO_TIMBRADO,
    FECHA_INSERT
) VALUES (
    5,
    '2011/11/01',
    2,
    2,
    2,
    3,
    'RAMP',
    1,
    'F001',
    'A',
    'COMPRA',
    '1234123',
    SYSDATE
);


-- INSERT DETALLE OPERACIONES
INSERT INTO D_DETALLE_OPERACIONES (
    ID_REGISTRO,
    ID_OPERACION,
    ID_PRODUCTO,
    COD_MEDIDA,
    CANTIDAD_OPERACION,
    PRECIO_OPERACION,
    IMPORTE_OPERACION,
    IMPORTE_DESCUENTO,
    COD_TIPO_IVA,
    PORCENTAJE_IVA,
    IMPORTE_IVA,      
    IMPORTE_RECARGO
) VALUES (
    21,
    5,
    2,
    1,
    3,
    5000000,
    15000000,
    50,
    1,
    10,
    100,
    5000000
);