-- item1
SELECT MAX(MVO.ID_OPERACION) AS MAX_ID,
    DEO.ID_PRODUCTO AS ID_PRODUCTO,
FROM D_MOVIMIENTO_OPERACIONES MVO
JOIN D_SUCURSAL SUC ON SUC.COD_SUCURSAL = MVO.COD_SUCURSAL
JOIN D_OPERACIONES OPE ON OPE.COD_OPERACION = MVO.COD_OPERACION
JOIN D_DETALLE_OPERACIONES DEO ON DEO.ID_OPERACION = MVO.ID_OPERACION
WHERE SUC.DESC_SUCURSAL LIKE '%CASA CENTRAL%' 
AND MVO.TIPO_REGISTRO = 'A'
AND OPE.DESC_OPERACION LIKE '%COMPRA%'
GROUP BY 
    DEO.PRECIO_OPERACION, 
    DEO.ID_PRODUCTO, 
    FECHA_OPERACION
ORDER BY  MAX_ID DESC;