UPDATE D_PRODUCTOS
SET (fecha_ultima_compra, precio_ultima_compra) = (
    SELECT MOP.FECHA_OPERACION, DOP.PRECIO_OPERACION  FROM D_DETALLE_OPERACIONES DOP
    INNER JOIN D_MOVIMIENTO_OPERACIONES MOP ON DOP.ID_OPERACION = MOP.ID_OPERACION
    INNER JOIN D_SUCURSAL SUC ON SUC.COD_SUCURSAL = MOP.COD_SUCURSAL
    INNER JOIN D_OPERACIONES O ON MOP.COD_OPERACION = O.COD_OPERACION
    WHERE O.DESC_OPERACION LIKE '%VENTA%' AND 
        SUC.DESC_SUCURSAL LIKE '%CASA CENTRAL%' AND
        MOP.TIPO_REGISTRO = 'A' AND
        D_PRODUCTOS.ID_PRODUCTO = DOP.ID_PRODUCTO
    ORDER BY MOP.FECHA_OPERACION, DOP.ID_OPERACION DESC
    FETCH FIRST ROW ONLY 
    )
WHERE fecha_ultima_compra IS NULL;


