-- Enunciado 1
-- ITEM 1
CREATE TABLESPACE BDHISTORICO
    DATAFILE 'C:\app\eduar\product\18.0.0\oradata\BDHISTORICO.dbf' SIZE 100M 
    DEFAULT STORAGE (INITIAL 100M NEXT 50K)
ONLINE;

-- ITEM 2
-- Create a new relational table called "D_COMPRAS_X_ANIO"
CREATE TABLE D_COMPRAS_X_ANIO 
(
    ANIO NUMBER(4) NOT NULL,
    ID_PRODUCTO NUMBER(12) NOT NULL,
    CANTIDAD NUMBER(12,2) DEFAULT 0 NOT NULL,
    MONTO NUMBER(15) DEFAULT 0 NOT NULL,
    USUARIO_ACT VARCHAR2(30) DEFAULT USER NOT NULL,
    FECHA_ACT DATE DEFAULT SYSDATE NOT NULL,
    CONSTRAINT D_COMPRAS_X_ANIO_PK PRIMARY KEY (ANIO, ID_PRODUCTO)
) TABLESPACE BDHISTORICO;

ALTER TABLE D_COMPRAS_X_ANIO ADD CONSTRAINT D_COMPRAS_X_ANIO_FK
FOREIGN KEY (ID_PRODUCTO)
REFERENCES D_PRODUCTOS (ID_PRODUCTO)
NOT DEFERRABLE;


-- Create a new relational table called "D_VENTAS_X_ANIO"
CREATE TABLE D_VENTAS_X_ANIO 
(
    ANIO NUMBER(4) NOT NULL,
    ID_PRODUCTO NUMBER(12) NOT NULL,
    CANTIDAD NUMBER(12,2) DEFAULT 0 NOT NULL,
    MONTO NUMBER(15) DEFAULT 0 NOT NULL,
    USUARIO_ACT VARCHAR2(30) DEFAULT USER NOT NULL,
    FECHA_ACT DATE DEFAULT SYSDATE NOT NULL,
    CONSTRAINT D_VENTAS_X_ANIO_PK PRIMARY KEY (ANIO, ID_PRODUCTO)
) TABLESPACE BDHISTORICO;

ALTER TABLE D_VENTAS_X_ANIO ADD CONSTRAINT D_VENTAS_X_ANIO_FK
FOREIGN KEY (ID_PRODUCTO)
REFERENCES D_PRODUCTOS (ID_PRODUCTO)
NOT DEFERRABLE;



-- ITEM 3
ALTER TABLE D_PERSONAS ADD
(
    fecha_nacimiento date,
    fecha_alta date 
        DEFAULT SYSDATE NOT NULL, 
    monto_deuda  NUMBER(12) 
        DEFAULT 0 NOT NULL,
    limite_credito NUMBER(12) 
        DEFAULT 5000000 NOT NULL,
    tipo_persona varchar2(1) 
        DEFAULT 'F' NOT NULL
        CONSTRAINT tipo_persona_check
        CHECK (tipo_persona IN ('F', 'J'))
);

alter table D_PERSONAS 
    add constraint fecha_alta_check 
        check(fecha_nacimiento is not null and (fecha_alta > fecha_nacimiento))
    ENABLE NOVALIDATE;

-- ITEM 4
ALTER TABLE D_PERSONAS ADD
CONSTRAINT if_unique UNIQUE (ruc);

ALTER TABLE D_PERSONAS ADD CONSTRAINT persona_j 
    CHECK (tipo_persona = 'J' AND ruc is not null)
    ENABLE NOVALIDATE;
