MEMBER PROCEDURE ASIGNAR_MONTOS IS
    V_IMPORTE_IVA NUMBER;
    V_MONTO_FACTURA NUMBER;
    V_IMPORTE_DESCUENTO NUMBER;
    V_IMPORTE_OPERACION NUMBER;
    BEGIN
        -- se recorre el arreglo de facturas
        FOR detalle IN SELF.DETALLE_FACTURA LOOP
            V_IMPORTE_OPERACION := V_IMPORTE_OPERACION + detalle.IMPORTE_OPERACION;
            V_IMPORTE_IVA := V_IMPORTE_IVA + detalle.IMPORTE_IVA;
            V_IMPORTE_DESCUENTO := V_IMPORTE_DESCUENTO + detalle.RECARGO_DESCUENTO;
        END LOOP;
        -- se asignan a la instancia del objeto
        SELF.MONTO_FACTURA := V_IMPORTE_OPERACION - V_IMPORTE_DESCUENTO + V_IMPORTE_IVA;
        SELF.MONTO_IVA := V_IMPORTE_IVA;
    END;
END get_address;