CREATE OR REPLACE TYPE T_FACTURA AS OBJECT(
    TIMBRADO NUMBER(12),
    NRO_COMPROBANTE VARCHAR2(20),
    FECHA_FACTURA DATE,
    NOMBRE_CLIENTE VARCHAR2(80),
    RUC_CEDULA VARCHAR2(20),
    MONTO_FACTURA NUMBER(12),
    MONTO_IVA NUMBER(10),
    CONTABILIZADO VARCHAR2(1),
    DETALLE_FACTURA TAB_DETALLE,
    STATIC FUNCTION INSTANCIAR_FACTURA(id_operacion NUMBER) RETURN T_FACTURA,
    MEMBER PROCEDURE ASIGNAR_MONTOS
);