TYPE TAB_DETALLE IS OBJECT(
	DESC_PRODUCTO VARCHAR2(80),
    DESC_UNIDAD_MEDIDA VARCHAR2(30),
    CANTIDAD NUMBER(12,2),
    PRECIO_ULTIMA_COMPRA NUMBER(12,2),
    PRECIO NUMBER(12),
    IMPORTE_OPERACION NUMBER(12),
    RECARGO_DESCUENTO NUMBER(10),
    PORCENTAJE_IVA NUMBER(3),
    IMPORTE_IVA NUMBER(10)
);