SELECT 
    FP.DESC_FORMA_PAGO AS FORMA_PAGO,
    SUM(
        CASE 
            WHEN CJ.NRO_CAJA = 1
                THEN PO.IMPORTE_PAGO 
            ELSE 0
        END
    ) AS CAJA1,
    SUM(
        CASE 
            WHEN CJ.NRO_CAJA = 2
                THEN PO.IMPORTE_PAGO
            ELSE 0
        END
    ) AS CAJA2,
    SUM(
        CASE 
            WHEN CJ.NRO_CAJA = 3
                THEN PO.IMPORTE_PAGO
            ELSE 0
        END
    ) AS CAJA3,
    NVL(SUM(
        CASE 
            WHEN CJ.NRO_CAJA = 4
                THEN PO.IMPORTE_PAGO
            ELSE 0
        END
    ) ,0 )AS CAJA4
FROM D_FORMA_PAGO FP
JOIN D_PAGO_OPERACION PO ON PO.COD_FORMA_PAGO = FP.COD_FORMA_PAGO
JOIN D_MOVIMIENTO_OPERACIONES MVO ON MVO.ID_OPERACION = PO.ID_OPERACION
JOIN D_CAJAS CJ ON CJ.NRO_CAJA = MVO.NRO_CAJA
GROUP BY FP.DESC_FORMA_PAGO
ORDER BY FP.DESC_FORMA_PAGO;
