-- D_FORMA_PAGO
-- D_PAGO_OPERACION
-- D_MOVIMIENTO_OPERACIONES
-- D_CAJAS
-- JOIN ALL TABLES
SELECT FP.DESC_FORMA_PAGO AS FORMA_PAGO,
    (
        CASE WHEN CJ.DESC_CAJA = 'CAJA NRO 1'
                THEN SUM(PO.IMPORTE_PAGO)
        END
    ) AS 'CAJA1'
FROM D_FORMA_PAGO FP
JOIN D_CAJAS CJ
JOIN D_PAGO_OPERACION
