CREATE OR REPLACE TRIGGER NO_MODIFICAR_DETALLE_OPERACIONES
BEFORE DELETE OR UPDATE ON D_DETALLE_OPERACIONES
FOR EACH ROW
DECLARE
    V_ID_OPERACION NUMBER(12) := 0;
BEGIN
    SELECT ID_OPERACION INTO V_ID_OPERACION FROM D_PAGO_OPERACION
    WHERE ID_OPERACION = :NEW.ID_OPERACION;

    IF V_ID_OPERACION > 0 THEN
         RAISE_APPLICATION_ERROR(-2009,'NO SE PERMITE MODIFICAR O ELIMINAR DATOS DE ESTA TABLA');
    END IF;

EXCEPTION WHEN NO_DATA_FOUND THEN
    NULL;
END;
/

