CREATE OR REPLACE TRIGGER T_PAGOS
BEFORE DELETE OR UPDATE ON D_PAGO_OPERACION
FOR EACH ROW
BEGIN
    IF DELETING OR UPDATING THEN
       RAISE_APPLICATION_ERROR(-20011,'NO SE PERMITE ELIMINAR DATOS DE ESTA TABLA');
    END IF; 
END;
/