CREATE MATERIALIZED VIEW CIERRE
TABLESPACE BASECONTABLE
    BUILD IMMEDIATE
    REFRESH START WITH ROUND(SYSDATE-1)+20/24 NEXT ROUND(SYSDATE+1)+20/24
    AS

SELECT 
    FP.DESC_FORMA_PAGO,
    SUM(
    CASE
        WHEN CA.DESC_CAJA = 'CAJA NRO 1' THEN
            PO.IMPORTE_PAGO
        ELSE
            0
        
    END) AS CAJA1,
    SUM(
    CASE
        WHEN CA.DESC_CAJA = 'CAJA NRO 2' THEN
            PO.IMPORTE_PAGO
        ELSE
            0
    END) AS CAJA2,
    SUM(
    CASE
        WHEN CA.DESC_CAJA = 'CAJA NRO 3' THEN
            PO.IMPORTE_PAGO
        ELSE
            0
    END) AS CAJA3,
    SUM(
    CASE
        WHEN CA.DESC_CAJA = 'CAJA NRO 4' THEN
            PO.IMPORTE_PAGO
        ELSE
            0
    END) AS CAJA4
FROM D_FORMA_PAGO FP
INNER JOIN D_PAGO_OPERACION PO
    ON PO.COD_FORMA_PAGO = FP.COD_FORMA_PAGO
INNER JOIN D_MOVIMIENTO_OPERACIONES MO
    ON MO.ID_OPERACION = PO.ID_OPERACION
INNER JOIN D_CAJAS CA
    ON CA.NRO_CAJA = MO.NRO_CAJA
GROUP BY FP.DESC_FORMA_PAGO;